// <auto-generated />
using Leasing.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leasing.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250602085718_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Leasing.Models.DB.IRRDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Bulan")
                        .HasColumnType("int");

                    b.Property<decimal>("NilaiPV")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ID");

                    b.ToTable("IRRDetail");
                });

            modelBuilder.Entity("Leasing.Models.DB.LeasingInput", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("CicilanPerBulan")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("DP")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("LamaBulan")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("LeasingInput");
                });

            modelBuilder.Entity("Leasing.Models.DB.LeasingResult", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("IRR")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NPV10")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NPV20")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NPV30")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NPV40")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NPV50")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PresentasiKeuntungan")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ProfitLeasing")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SisaPembayaran")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalAngsuran")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id");

                    b.ToTable("LeasingResult");
                });

            modelBuilder.Entity("Leasing.Models.DB.PVDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bulan")
                        .HasColumnType("int");

                    b.Property<decimal>("NilaiPV")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("PVDetail");
                });

            modelBuilder.Entity("NPVChartPoint", b =>
                {
                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NPV")
                        .HasColumnType("decimal(65,30)");

                    b.ToTable("NPVChartPoint");
                });
#pragma warning restore 612, 618
        }
    }
}
